### ISSUE TITLE
When will the paper of 3DVG-Transformer+ be published?

### ISSUE THREAD

**Issue by jianghaojun** [zlccccc/3DVG-Transformer#1]
Quite impressive performance!

It seems the paper of 3DVG-Transformer+ (CVPR 2022) has not pulished yet.

**Comment by zlccccc** [comment]
3DVG-Transformer+ is an extension of our ICCV paper and has won the [1st Workshop on Language for 3D Scenes](https://language3dscenes.github.io/), and we did not publish a unique paper for this method.
To be specific, our self-attention blocks in the multiplex attention (MA) module in the cross-modal feature fusion stage follow the vanilla multi-head attention structure, which can be readily replaced by the coordinate-guided self-attention block (see Fig.2 (b) of our ICCV paper) with the aid of the additional spatial proximity matrix.
Code Link:
https://github.com/zlccccc/3DVG-Transformer/blob/main/models/match_module.py#L12

**Comment by jianghaojun** [comment]
Thanks for your quick reply.
