### ISSUE TITLE
IndexError during evaluation...

### ISSUE THREAD

**Issue by timzsu** [zlccccc/3DVG-Transformer#3]
I have successfully trained the model, but when I try to evaluate the result, it reported an IndexError to me. It seems that the shape of mask[i] didn't align with the shape of ref_acc[i], but I have had a hard time trying to figure out how to solve it. Have anyone met the same problem? How can I fix it? 

The command I used:
python scripts/ScanRefer_eval.py --folder /share/suzhengyuan/ScanRefer-3DVG/3DVG-Transformer-orig/outputs/2022-04-25_01-35-11 --reference --use_color --force

The output:
evaluate localization...
preparing data...
loading data...
evaluate on 363 samples
{'mask': 'no_mask', 'weighted_input': True, 'transformer_type': 'myAdd_20;deformable', 'deformable_type': 'myAdd', 'position_embedding': 'none', 'input_dim': 0, 'enc_layers': 0, 'dec_layers': 2, 'dim_feedforward': 2048, 'hidden_dim': 288, 'dropout': 0.1, 'nheads': 8, 'pre_norm': False} << config transformer 
[build transformer] Using transformer type myAdd_20;deformable
{'mask': 'no_mask', 'weighted_input': True, 'transformer_type': 'myAdd_20;deformable', 'deformable_type': 'myAdd', 'position_embedding': 'none', 'input_dim': 0, 'enc_layers': 0, 'dec_layers': 2, 'dim_feedforward': 2048, 'hidden_dim': 288, 'dropout': 0.1, 'nheads': 8, 'pre_norm': False} << transformer config
[Attention:] The Transformer Model Have Decoder Module
Attention input type myAdd_20
transformer: Using Decoder transformer type myAdd_20 deformable
gelu << transformer activation
[INFO!] Use Weighted Input!
evaluating...
generating the scores for seed 42...
  0%|                                                                                                                                         | 0/46 [00:00<?, ?it/s]/share/anaconda3/envs/instref/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [03:39<00:00,  4.76s/it]
Traceback (most recent call last):
  File "/share/suzhengyuan/ScanRefer-3DVG/3DVG-Transformer-orig/scripts/ScanRefer_eval.py", line 489, in <module>
    if args.reference: eval_ref(args)
  File "/share/suzhengyuan/ScanRefer-3DVG/3DVG-Transformer-orig/scripts/ScanRefer_eval.py", line 298, in eval_ref
    running_ref_acc = np.mean(ref_acc[i][np.logical_and(masks[i] == multiple_dict[k], others[i] == others_dict[k_o])]) \
IndexError: boolean index did not match indexed array along dimension 0; dimension is 11616 but corresponding boolean dimension is 9508

**Comment by zlccccc** [comment]
For a fair comparison with ScanRefer, we need to set lang_num_max to 1 during testing, and the current codebase does not support lang_num_max!=1 when testing.
The bug is fixed now.
https://github.com/zlccccc/3DVG-Transformer/blob/main/scripts/ScanRefer_eval.py#L459

**Comment by zlccccc** [comment]
Note that the results generated by ScanRefer_eval.py may be slightly lower than the test results during training. The main reason is that the results of model testing fluctuate, while the maximum value is reported during training, and we do not use a fixed test seed.
