### ISSUE TITLE
The file lib/config.py is missing...

### ISSUE THREAD

**Issue by jianghaojun** [zlccccc/3DVG-Transformer#4]
Besides, why not directly integrate the data folder from ScanRefer into your repo?

**Comment by zlccccc** [comment]
fixed.

**Comment by zlccccc** [comment]
Last year, the preprocessing part of the ScanRefer dataset changed slightly (in the official repo). It is recommended to go to the official ScanRefer GitHub link to download the dataset. Here, I've incorporated the latest version of the preprocessing process in our repo.
Our paper reports the results when using the old preprocessing scheme, and our experimental results show that the results of the two preprocessing schemes are not much different.

**Comment by jianghaojun** [comment]
Thanks for your quick reply.
