### ISSUE TITLE
Can't achieve the results shown in the paper

### ISSUE THREAD

**Issue by silicon-bond** [zlccccc/3DVG-Transformer#7]
Dears,

Thank you very much for your amazing work!

I tried a lot of parameter settings, but still can't achieve the results shown in the paper.I've been trying for a long time.

![X175YZ7LK@ER`)VGP2BIR}A](https://user-images.githubusercontent.com/79505663/208602312-91c28360-51f7-4a7e-9180-6434acb6d490.png)

So I would like to ask you for possible reasons.

Thanks for your help.

Best

**Comment by zlccccc** [comment]
Sorry for the late reply.
It appears that the results in your picture are 1~2% better than those reported in our paper in case of acc @ 0.25iou and acc @ 0.5iou (48.67 _vs._ 47.57; 36.15 _vs._ 34.67).  This may be due to training fluctuations or different hyperparameter settings.

**Comment by Andy20178** [comment]
Hello! How long does your training take? I'm using Nvidia RTX 3090, and the training time exceeds 45 hours with the '--use multiview' option, with most of the time spent on loading HDF5 data. How do you replicate the author's results?
